version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: luestilo
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  tests:
    build: .
    command: ["pytest"]
    volumes:
      - .:/code
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /code
    environment:
      - PYTHONPATH=/code


volumes:
  postgres_data:
